############# English navigation ##############

# main menu

[[main]]
name = "Events"
url = "events/"
weight = 1

[[main]]
name = "Photos"
url = "photos/"
weight = 2

[[main]]
name = "Toolkit"
hasChildren = true
url = "toolkit/"
weight = 3

  [[main]]
  parent = "Toolkit"
  name = "All toolkits"
  url = "toolkit/"
  weight = 1

  [[main]]
  parent = "Toolkit"
  name = "Canvas shelter"
  url = "toolkit/canvas/"
  weight = 2

  [[main]]
  parent = "Toolkit"
  name = "Storage unit"
  url = "toolkit/storage/"
  weight = 3

  [[main]]
  parent = "Toolkit"
  name = "CAD"
  url = "toolkit/cad/"
  weight = 4

  [[main]]
  parent = "Toolkit"
  name = "Gabion"
  url = "toolkit/gabion/"
  weight = 5

  [[main]]
  parent = "Toolkit"
  name = "Mint hex beds"
  url = "toolkit/hexbeds/"
  weight = 6

[[main]]
name = "Ecology"
hasChildren = true
weight = 4

  [[main]]
  parent = "Ecology"
  name = "Your Wild Patch"
  url = "your-wild-patch/"
  weight = 1

  [[main]]
  parent = "Ecology"
  name = "Plants spreadsheet"
  url = "plants/"
  weight = 2

  [[main]]
  parent = "Ecology"
  name = "Species spreadsheet"
  url = "species/"
  weight = 3

  [[main]]
  parent = "Ecology"
  name = "Native ground cover"
  url = "ground-cover/"
  weight = 4

# footer menu

[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "Contact"
url = "contact/"
weight = 2

[[footer]]
name = "Archive"
url = "archive/"
weight = 3

[[footer]]
name = "Licensing"
url = "licensing/"
weight = 4
