############# Welsh navigation ##############

# main menu
[[main]]
name = "Cylchlythyr"
url = "cylchlythyr/"
weight = 1

[[main]]
name = "Blog"
url = "blog/"
weight = 2

[[main]]
weight = 5
name = "Tudalennau"
hasChildren = true

  [[main]]
  parent = "Tudalennau"
  name = "Pecyn cymorth"
  url = "pecyn_cymorth/"
  weight = 1

  [[main]]
  parent = "Tudalennau"
  name = "Partneriaid"
  url = "partneriaid/"
  weight = 2

  [[main]]
  parent = "Tudalennau"
  name = "Amdanom ni"
  url = "amdanom_ni/"
  weight = 3

  [[main]]
  parent = "Tudalennau"
  name = "Tîm"
  url = "tîm/"
  weight = 4

  [[main]]
  parent = "Tudalennau"
  name = "Cysylltu"
  url = "cysylltu/"
  weight = 6

[[main]]
name = "Gweinyddu"
hasChildren = true
weight = 5

  [[main]]
  parent = "Gweinyddu"
  name = "Gweithdai"
  url = "gweithdai/"
  weight = 1

  [[main]]
  parent = "Gweinyddu"
  name = "Calendr digwyddiadau"
  url = "digwyddiadau/"
  weight = 2

  [[main]]
  parent = "Gweinyddu"
  name = "Taenlen planhigion"
  url = "planhigion/"
  weight = 3

  [[main]]
  parent = "Gweinyddu"
  name = "Pecyn cyfryngau"
  url = "cyfryngau/"
  weight = 4

[[main]]
name = "Grant"
hasChildren = true
weight = 6

  [[main]]
  parent = "Grant"
  name = "Trosolwg"
  url = "grant/trosolwg/"
  weight = 1

  [[main]]
  parent = "Grant"
  name = "Cais"
  url = "grant/cais/"
  weight = 2

  [[main]]
  parent = "Grant"
  name = "Dibenion"
  url = "grant/dibenion/"
  weight = 3

  [[main]]
  parent = "Grant"
  name = "Cynnal"
  url = "grant/cynnal/"
  weight = 4

  [[main]]
  parent = "Grant"
  name = "Perfformiad"
  url = "grant/perfformiad/"
  weight = 5

  [[main]]
  parent = "Grant"
  name = "Prosiect"
  url = "grant/prosiect/"
  weight = 5

# footer menu
[[footer]]
name = "Trwyddedu"
url = "trwyddedu/"
weight = 1
