########################### Default parameters ######################
logo = "https://res.cloudinary.com/hopegarden/image/upload/v1719952233/logo.svg"
logo_width = "60px"
logo_footer = "https://res.cloudinary.com/hopegarden/image/upload/v1719952045/logotype-wo.png"
favicon = "https://res.cloudinary.com/hopegarden/image/upload/v1719952222/favicon.png"
# Top header
top_header = true
# Meta data
description = "Community Assembly at the heart of a wildlife forest garden"
author = "Garden Wild Plants CIC"
# Contact info
address = "Pen Y Foidr, Cilgerran, Pembrokeshire SA43 2TH"
mobile = "07802 535 321"
email = "hello@hopegarden.uk"
# Contact form action
contact_form_action = "https://formspree.io/f/{form_id}" # contact form works with https://formspree.io
# Google Analytics
# google_analitycs_id = "" # your id
# page sidebar quick contact form
quick_contact = true
# Search
search = true

# Main section
mainSections = ["blog"]

# Preloader
[preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Navigation button
[navigation_button]
enable = false
label = "Get a life"
link = "contact/"

# Subscription
[subscription]
enable = true
# newsletter subsciption
newsletter_form_action = "https://buttondown.email/api/emails/embed-subscribe/hopegarden" # replace this url with yours

# Google map
[gmap]
enable = true
gmap_api = "{GMAP_API}"
map_latitude = "52.05221122856925"
map_longitude = "-4.633375693549827"
# map_marker = "images/marker.png"
# map_marker_name = "Hope Garden"

########################### social icon ############################
[[social]]
icon = "fab fa-mastodon"
link = "https://climatejustice.social/@hopegarden"

[[social]]
icon = "fab fa-facebook"
link = "https://facebook.com/hopegardenuk"

[[social]]
icon = "fab fa-twitter"
link = "https://x.com/hopegardenuk"

[[social]]
icon = "fab fa-tiktok"
link = "https://tiktok.com/@hopegardenuk"

[[social]]
icon = "fab fa-youtube"
link = "https://youtube.com/@hopegardenuk"


# [[social]]
# icon = "fab fa-instagram"
# link = "https://instagram.com/hopegardenfuture"

[[social]]
icon = "fab fa-github"
link = "https://github.com/hopegardenuk"

